name: vigaviga
description: "Blockchain arts project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  dio: ^5.0.0
  flutter_screenutil: ^5.9.3
  logging: ^1.2.0
  vibration: ^3.1.2
  mobile_scanner: ^7.0.1
  lottie: ^3.1.2
  video_player_win: ^3.1.1
  video_player: ^2.9.3
  dotted_border: ^3.1.0
  path_provider: ^2.1.5
  path: ^1.9.0
  http: ^1.3.0
  crypto: ^3.0.6
  get_thumbnail_video: ^0.7.3
  record: ^6.1.1
  uuid: ^4.5.1
  image_picker: ^1.2.0
  camera: ^0.11.0+2
  collection: ^1.19.0
  flutter_in_app_pip: ^1.7.4
  webview_windows: ^0.4.0
  floating: ^6.0.0
  image_size_getter: ^2.4.1
  webview_flutter: ^4.13.0
  permission_handler: ^12.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^16.2.1
  cupertino_icons: ^1.0.6
  vector_math: ^2.1.2
  cached_network_image: ^3.4.1
  fluttertoast: ^9.0.0
  archive: ^4.0.7
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  flutter_inappwebview: ^6.1.5
  mime: ^2.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/lotties/
    - assets/web/
  fonts:
    # - family: AlibabaPuHuiTi
    #   fonts:
    #     - asset: ./assets/fonts/AlibabaPuHuiTi-3-55-Regular.woff2
    # - family: AlibabaPuHuiTi-Medium
    #   fonts:
    #     - asset: ./assets/fonts/AlibabaPuHuiTi-3-65-Medium.woff2
    # - family: NotoColorEmoji-Regular
    #   fonts:
    #     - asset: ./assets/fonts/NotoColorEmoji-Regular.woff2

    # - family: Roboto
    #   fonts:
    #     - asset: ./assets/fonts/Roboto.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/google_fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/google_fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/google_fonts/Roboto-Bold.ttf
          weight: 700
    - family: Iconfont
      fonts:
        - asset: ./assets/fonts/iconfont/iconfont.ttf

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "assets/images/icon/1.jpeg"
    background_color: "#0175C2"
    theme_color: "#0175C2"
